language: ruby
rvm:
- 2.1.0
before_install:
- openssl aes-256-cbc -K $encrypted_6c622337aa90_key -iv $encrypted_6c622337aa90_iv -in deploy-key.enc -out deploy-key -d
- chmod 600 deploy-key
- mv deploy-key ~/.ssh/id_rsa
- openssl rsa -in ~/.ssh/id_rsa -out ~/.ssh/id_rsa -passin pass:"$DEPLOY_PASS"
- echo -e "Host ppmroadmap.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
script:
- if [ $TRAVIS_BRANCH == 'sl-dist' ] ; then
    ssh root@ppmroadmap.com 'cd /var/www/michael.ppmroadmap.com/production; rm -rf current; mkdir current';
    # scp -r * root@ppmroadmap.com:/var/www/michael.ppmroadmap.com/production/current;
  else
    echo "I'm not deploying since this branch isn't sl-dist.";
  fi
branches:
  only:
  - sl-dist
