language: ruby
rvm:
- 2.1.0
before_install:
- echo "$DEPLOY_KEY" > deploy_key
- chmod 600 deploy_key # this key should have access to server
- mv deploy_key ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- echo -e "Host ppmroadmap.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
script:
- if [ $TRAVIS_BRANCH == 'sl-dist' ] ; then
    scp -v .travis.yml root@ppmroadmap.com:/var/www/michael.ppmroadmap.com/production/current;
  else
    echo "I'm not deploying since this branch isn't sl-dist.";
  fi
branches:
  only:
  - sl-dist
