# A sample Gemfile
source "https://rubygems.org"

# gem "rails"
gem "breakpoint"
gem "capistrano", "2.15.4"
gem "capistrano-ext"
gem "compass"
gem "compass-import-once"
gem "hologram"
gem "hpricot"
gem "html-proofer"
gem "jekyll"
gem "jekyll-import"
gem "jekyll-itafroma-archive"
gem "railsless-deploy"
gem "sass"
gem "sassy-maps"
gem "susy"
gem "travis"
gem "mini_magick"
